[package]
name = "systemstat"
version = "0.1.2"
authors = [ "Greg V <greg@unrelenting.technology>" ]
keywords = [ "System", "Info" ]
description = "systemstat"
license = "Unlicense"
readme = "README.md"
homepage = "https://github.com/myfreeweb/systemstat"
repository = "https://github.com/myfreeweb/systemstat"

[dependencies]
time = "0.1"
chrono = "0.4"
lazy_static = "0.2"
bytesize = "0.1"
uptime_lib = "0.1"

[target.'cfg(target_os = "linux")'.dependencies]
nom = "3.2"

[target.'cfg(not(windows))'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"
